### ISSUE TITLE
FUCK YOU ! The eggs kill command kills entire linux system.

### ISSUE THREAD

**Issue by ghost** [pieroproietti/penguins-eggs-legacy#266]
FUCK YOU
You just fucked my entire server and project. Im reporting you and your account for this shit.

**Comment by un-simp** [comment]
Hey dude. the fact that eggs killed your system isn't Piero's fault. this is the importance of auditing code before you run it on your system, cause bugs like this can and sometimes will happen. Looking at the code (i dont know that much typescript but i can read it) it takes the config and just rm -rf
while ideally it should confirm the directories like "/home/user/pengiun-eggs" will be removed or something. Its either to do with symlinks created in the system or a bad config

**Comment by un-simp** [comment]
Also. i saw the original message. Death threats are just not acceptable even in a case like this. They don't get anything done and can be damaging to peoples mental health.

**Comment by ghost** [comment]
> Also. i saw the original message. Death threats are just not acceptable even in a case like this. They don't get anything done and can be damaging to peoples mental health.

Thats why i deleted it, it was too much, i was just pisssed

**Comment by pieroproietti** [comment]
Se c'era un dubbio sul fatto che i coglioni esistono, beh ci siamo tolti la soddisfazione.

**Comment by fearlessgeekmedia** [comment]
Not cool with the death threats. Good on you for recognizing it was wrong and removing them. But hopefully you try to keep your cool with this sort of stuff, and make backups. 

But out of curiosity, was this on real hardware or a VM? If it was real hardware, I just learned Piero only tests on VMs, not real hardware. He doesn't have time, apparently. It seems like with a project like this, it should be important enough to make time to test it on real hardware, or delegate it to someone who does have the time and resources. 

I made my issue known and found it's only tested on VMs. He's just trusting it's working for others on real hardware because no one has said anything about it. But I said something about it.

So this seems to me to be a serious problem with a project like this. It really needs more testing on real hardware. If it's not going to be, it's hard for me to take this project seriously. 

Or at least he needs a disclaimer saying that it hasn't been tested on real hardware, and that using this is at your own risk.
