### ISSUE TITLE
No internet after sudo eggs produce / sudo eggs produce --clone

### ISSUE THREAD

**Issue by zDEFz** [pieroproietti/penguins-eggs-legacy#305]
No clue what causes this - a reboot solves it. 
I used to think this was intentional - but I now doubt it.

**Comment by pieroproietti** [comment]
No, it is not intentional and really I don't know why this happen, but I can confirm.

Perhaps, during the process of build live, we use a live filesystem created with binded dirs from the real. I use same dirs R/W using overlay and [here](https://github.com/pieroproietti/penguins-eggs/blob/37964fe7edfecc31a776cd502cdfc68a42b09c9d/src/classes/ovary.ts#L481) I remove /etc/resolv.conf.

**Comment by pieroproietti** [comment]
The problem arise from the service `systemd-resolved.service`, a workaround without reboot, is: `sudo systemctl restart systemd-resolved.service`
