### ISSUE TITLE
Issue with some directory under /var/log in debian 10

### ISSUE THREAD

**Issue by dimebage** [pieroproietti/penguins-eggs-legacy#327]
First of all thanks for this great tools.very valuable and neat.
We have tried this on debian 10 64 bit with lots of tools and customization done on it and so far everything seems to work.
There are two minor issue thats maybe our fault though
1- Some directories under /var/log seems not to be copied or deployed correctly.We have apache redis-server mysql and these directory does not get created after installing which cause the services not to start upon first start.
2-We do want to keep root user login in  sshd_config enabled i changed the flag in /etc/penguins-eggs.d/eggs.yaml  to ssh_pass: true but still the installer does not correctly recognize it. it still removes the permitrootlogin lines from sshd config which cause the root user not able to login after image is deployed. 
other than that everything seems to work great.
By the way the image is created in this way .
eggs produce --clone
Regards

**Comment by pieroproietti** [comment]
@dimebage 

Thanks for you comment, well looking the questions:

1) eggs use an exclude.list, we lately changed how it work, but in all the ways actually we have same files on `/etc/penguins-eggs.d`: `exclude.list.template` is always used, `exclude.list.homes`, and `exclude.list.custom`. The last two are used or not depending on the flag `--filters`.

On `exclude.list.template` you have the line `var/log/*`, you must to delete or comment it in order to have your logs. Probably is better to insert `var/log/redis/*` to have just directory but not all the logs on the ISO, the same for mysql. 

Probably I will this behaviour too.

2) use flag `--unsecure` in produce, I gave it this great name, but all it do is to add to the exclusions  `root/*` and `root/.*`.

3) this is mine: if you are using `--clone`, root must to be included in the live image, almost as far as I remember.

**Comment by dimebage** [comment]
Thank you, Both issue fixed as per your guide.

**Comment by pieroproietti** [comment]
I updated eggs too, and I think from version 9.6.26 you will not get more this problem.
