### ISSUE TITLE
Feature request: Desktopless install

### ISSUE THREAD

**Issue by vaultdweller-2287** [pieroproietti/penguins-eggs-legacy#438]
I was wondering if there was a way to have a full CLI/TUI install for penguins eggs. Not in a way where its a headless system but the graphical interface is used after install. Krill works well but I would prefer it to be fullscreen.

**Comment by pieroproietti** [comment]
krill is made with [ink](https://github.com/vadimdemedes/ink) for the TUI, so it adapt to the size of the screen.

Certainly there are areas where it could be improved, especially on the disk management side, coexistence of multiple operating systems on one disk, etc.

One idea of mine, which I may put into practice, is to detach it from eggs and have it work on its own, since there is some interest in a TUI installer, especially if it is compatible -- albeit partially -- with calamares configurations.

Unfortunately, though, it takes time and I'm only in development, so hopefully some developers might be interested.

Thanks for you attention.

**Comment by vaultdweller-2287** [comment]
Thanks for the response! Interesting how Krill works like that, I'll look at it further!
